# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Building & Releasing

on:
  release:
    types: [published]
    
permissions:
  contents: write

env:
  VERSION: ${{ github.ref_name }}
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json

    - name: Update Manifest Version
      run: |
         sed -i "s|version \"[^\"]*\"|version \"${VERSION}\"|" fxmanifest.lua

    - name: Build Client UI
      run: |
        cd ui
        npm install
        npm run build

    - name: Create Releasable
      run: |
       ls -alr
       rm -rf ui/public
       rm -rf ui/src
       rm -rf ui/package.json
       rm -rf ui/package-lock.json
       rm -rf ui/tsconfig.json
       rm -rf ui/node_modules
       rm -rf ui/vite.config.ts
       rm -rf .github
       rm -rf .git
       cd ..
       zip -r sz_multijob/sz_multijob-${VERSION}.zip sz_multijob/ -x "sz_multijob/sz_multijob-*.zip"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: sz_multijob-${{ github.ref_name }}
          path: sz_multijob-${{ github.ref_name }}.zip

    - name: Upload renamed release asset
      uses: softprops/action-gh-release@v2
      with:
        files: sz_multijob-${{ github.ref_name }}.zip
