# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Building & Releasing

on:
  release:
    types: [published]
    
permissions:
  contents: write
  
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: 'sz_multijob'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: sz_multijob/ui/package-lock.json
    - run: npm ci
    - run: npm run build

    - name: Create Releasable
      run: |
       rm -rf sz_multijob/ui/public
       rm -rf sz_multijob/ui/src
       rm -rf sz_multijob/ui/package.json
       rm -rf sz_multijob/ui/package-lock.json
       rm -rf sz_multijob/ui/tsconfig.json
       rm -rf sz_multijob/ui/vite.config
       zip -r sz_multijob-${VERSION}.zip sz_multijob/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: sz_multijob-${{ github.ref_name }}
          path: sz_multijob-${{ github.ref_name }}.zip

    - name: Upload renamed release asset
      uses: softprops/action-gh-release@v2
      with:
        files: sz_multijob-${{ github.ref_name }}.zip
